### ISSUE TITLE
Format Progress with only two digits

### ISSUE THREAD

**Issue by MatheusMoura17** [jlsneto/cereja#31]
* **Version**: 1.1.0

Currently, the **ProgressBar** is returning percentage value with large numbers, see the image below:

![image](https://user-images.githubusercontent.com/6765023/76859702-97a74300-6838-11ea-9781-7ee2809aefd7.png)

It's cool maintaining the progress bar with two digits:

current: `3.9012......%`
sugestion: `03.90%`

**Comment by jlsneto** [comment]
[Fix me: Line 188](https://github.com/jlsneto/cereja/blob/66b7ef86a77140429f75e4dae3606c6abacac72f/cereja/display.py#L188)
