### ISSUE TITLE
Progress is not completing for small values

### ISSUE THREAD

**Issue by MatheusMoura17** [jlsneto/cereja#32]
* **Version**: 1.1.0.final.0
* **Platform**: Linux 00c891b4b673 4.14.137+ #1 SMP Thu Aug 8 02:47:02 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

## Resume
Passing small values (i have tested with values below of 10) the Progress is not completing.
Sample:

```
import cereja as cj

with cj.Progress('Progress', style='bar', max_value=10) as bar:
  for i in range(10):
    bar.update(i)
```

expected on finish operation:

```
🍒 Progress: [=============================>] Done! ✅ - Time: 0.5s
```

current behaviour:

```
🍒 Progress: [===========================>  ] Done! ✅ - Time: 0.5s
```

**Comment by jlsneto** [comment]
I think that's because the thread dies when it goes out of context. I need to wait for the result to be displayed completely to the user. This is a matter of milliseconds.

**Comment by jlsneto** [comment]
note that the range (10) never reaches 10, the range function is like this, your last update will be 9. But there is still a bug when displaying Done's message.

```
import cereja as cj

with Progress('Progress', style='bar', max_value=9) as bar:
    for i in range(0, 10):
        bar.update(i)
```
> `🍒 Progress: [==============================] Done! ✅ - Time: 0.01s`
